In [5]:
import pandas as pd #for data wrangling
pd.set_option('display.max_rows',None)

In [6]:
df=pd.read_csv("cricinfos.csv")

In [7]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,-,15,19,6,258,2
9,HC Brook (ENG),2022-2024,24,40,1,2281,317,58.48,2581,88.37,8,10,2,246,37
10,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
12,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
13,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
14,SPD Smith (AUS),2010-2025,116,206,25,10271,239,56.74,19176,53.56,36,41,11,1116,61
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,-,15,14,1,107,11
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
18,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2
19,KS Williamson (NZ),2010-2024,105,186,17,9276,251,54.88,17913,51.78,33,37,11,1031,27
20,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1
21,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
22,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
23,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6
24,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69
25,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
26,YBK Jaiswal (IND),2023-2025,19,36,2,1798,214*,52.88,2738,65.66,4,10,3,207,39
27,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48
28,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
29,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
30,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
31,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
32,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3
33,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
34,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
35,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
36,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26
37,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
38,JE Root (ENG),2012-2024,152,278,23,12972,262,50.87,22568,57.47,36,65,13,1394,45
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.1,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
41,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28
42,Saud Shakeel (PAK),2022-2025,19,36,3,1658,208*,50.24,3345,49.56,4,9,2,165,2
43,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84
44,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3
45,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
46,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
47,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11
48,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0
49,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91
50,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
51,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
52,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20
53,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1
54,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,-,-,5,6,3,51,0
55,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
56,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [8]:
df["country"]=df["Player"].str.split(pat="(").str[1]
df["country"]=df["country"].str.split(pat="(").str[0]
df["Player"]=df["Player"].str.split(pat="(").str[0]
df["start_year"]=df["Span"].str.split(pat="-").str[0].astype(int)
df["end_year"]=df["Span"].str.split(pat="-").str[1].astype(int)
df.rename(columns={"Span":"Duration","Mat":"Matches","BF":"Balls_faced","HS":"High_score","SR":"Strike_rate"},inplace=True)
df["Duration"]=df["end_year"]-df["start_year"] 
df["High_score"]=df["High_score"].str.split(pat="*").str[0].astype(int)
df["Balls_faced"]=df["Balls_faced"].str.split(pat="+").str[0]
df["Balls_faced"]=df["Balls_faced"].replace("-",0)
df["Balls_faced"]=df["Balls_faced"].astype(int)
df["Strike_rate"]=df["Strike_rate"].replace("-",0)
df["Strike_rate"]=df["Strike_rate"].astype(float)
df["0"]=df["0"].replace("-",0)
df["0"]=df["0"].astype(int)

In [30]:
df

,Player,Duration,Matches,Inns,NO,Runs,High_score,Ave,Balls_faced,Strike_rate,100,50,0,4s,6s,country,start_year,end_year
0,DG Bradman,20,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS),1928,1948
1,PHKD Mendis,3,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL),2022,2025
2,AC Voges,1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),2015,2016
3,RG Pollock,7,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA),1963,1970
4,GA Headley,24,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI),1930,1954
5,H Sutcliffe,11,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG),1924,1935
6,E Paynter,8,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG),1931,1939
7,KF Barrington,13,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG),1955,1968
8,ED Weekes,10,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,WI),1948,1958
9,HC Brook,2,24,40,1,2281,317,58.48,2581,88.37,8,10,2,246,37,ENG),2022,2024
10,WR Hammond,20,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG),1927,1947
11,GS Sobers,20,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,WI),1954,1974
12,KC Sangakkara,15,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,SL),2000,2015
13,JB Hobbs,22,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,ENG),1908,1930
14,SPD Smith,15,116,206,25,10271,239,56.74,19176,53.56,36,41,11,1116,61,AUS),2010,2025
15,CL Walcott,12,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,WI),1948,1960
16,L Hutton,18,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,ENG),1937,1955
17,JH Kallis,18,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,ICC/SA),1995,2013
18,GE Tyldesley,8,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,ENG),1921,1929
19,KS Williamson,14,105,186,17,9276,251,54.88,17913,51.78,33,37,11,1031,27,NZ),2010,2024
20,CA Davis,5,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,WI),1968,1973
21,VG Kambli,2,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,IND),1993,1995
22,GS Chappell,14,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,AUS),1970,1984
23,AD Nourse,16,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,SA),1935,1951
24,SR Tendulkar,24,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,IND),1989,2013
25,BC Lara,16,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,ICC/WI),1990,2006
26,YBK Jaiswal,2,19,36,2,1798,214,52.88,2738,65.66,4,10,3,207,39,IND),2023,2025
27,Javed Miandad,17,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,PAK),1976,1993
28,R Dravid,16,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,ICC/IND),1996,2012
29,Mohammad Yousuf,12,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,PAK),1998,2010
30,Younis Khan,17,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,PAK),2000,2017
31,RT Ponting,17,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,AUS),1995,2012
32,J Ryder,9,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,AUS),1920,1929
33,A Flower,10,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,ZIM),1992,2002
34,MEK Hussey,8,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,AUS),2005,2013
35,S Chanderpaul,21,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,WI),1994,2015
36,SM Gavaskar,16,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,IND),1971,1987
37,SR Waugh,19,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,AUS),1985,2004
38,JE Root,12,152,278,23,12972,262,50.87,22568,57.47,36,65,13,1394,45,ENG),2012,2024
39,ML Hayden,15,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,AUS),1994,2009
40,AB de Villiers,14,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,SA),2004,2018
41,AR Border,16,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,AUS),1978,1994
42,Saud Shakeel,3,19,36,3,1658,208,50.24,3345,49.56,4,9,2,165,2,PAK),2022,2025
43,IVA Richards,17,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,WI),1974,1991
44,DCS Compton,20,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,ENG),1937,1957
45,DPMD Jayawardene,17,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,SL),1997,2014
46,Inzamam-ul-Haq,15,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,ICC/PAK),1992,2007
47,FMM Worrell,15,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,WI),1948,1963
48,CP Mead,17,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,ENG),1911,1928
49,V Sehwag,12,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,ICC/IND),2001,2013
50,Abid Ali,2,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,PAK),2019,2021
51,MJ Clarke,11,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,AUS),2004,2015
52,KC Bland,5,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,SA),1961,1966
53,B Mitchell,20,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,SA),1929,1949
54,Hon.FS Jackson,12,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,ENG),1893,1905
55,TT Samaraweera,12,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,SL),2001,2013
56,RN Harvey,15,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,AUS),1948,1963
57,KD Walters,16,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS),1965,1981
58,GC Smith,12,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),2002,2014
59,WH Ponsford,10,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS),1924,1934
60,SJ McCabe,8,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS),1930,1938
61,DR Jardine,6,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG),1928,1934

In [31]:
df.to_csv("newcricinfo.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'newcricinfo.csv'

In [24]:
df

,Player,Duration,Matches,Inns,NO,Runs,High_score,Ave,Balls_faced,Strike_rate,100,50,0,4s,6s,country,player,start_year,end_year
0,DG Bradman (AUS),20,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS),DG Bradman,1928,1948
1,PHKD Mendis (SL),3,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL),PHKD Mendis,2022,2025
2,AC Voges (AUS),1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges,2015,2016
3,RG Pollock (SA),7,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA),RG Pollock,1963,1970
4,GA Headley (WI),24,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI),GA Headley,1930,1954
5,H Sutcliffe (ENG),11,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG),H Sutcliffe,1924,1935
6,E Paynter (ENG),8,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG),E Paynter,1931,1939
7,KF Barrington (ENG),13,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG),KF Barrington,1955,1968
8,ED Weekes (WI),10,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,WI),ED Weekes,1948,1958
9,HC Brook (ENG),2,24,40,1,2281,317,58.48,2581,88.37,8,10,2,246,37,ENG),HC Brook,2022,2024
10,WR Hammond (ENG),20,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG),WR Hammond,1927,1947
11,GS Sobers (WI),20,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,WI),GS Sobers,1954,1974
12,KC Sangakkara (SL),15,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,SL),KC Sangakkara,2000,2015
13,JB Hobbs (ENG),22,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,ENG),JB Hobbs,1908,1930
14,SPD Smith (AUS),15,116,206,25,10271,239,56.74,19176,53.56,36,41,11,1116,61,AUS),SPD Smith,2010,2025
15,CL Walcott (WI),12,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,WI),CL Walcott,1948,1960
16,L Hutton (ENG),18,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,ENG),L Hutton,1937,1955
17,JH Kallis (ICC/SA),18,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,ICC/SA),JH Kallis,1995,2013
18,GE Tyldesley (ENG),8,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,ENG),GE Tyldesley,1921,1929
19,KS Williamson (NZ),14,105,186,17,9276,251,54.88,17913,51.78,33,37,11,1031,27,NZ),KS Williamson,2010,2024
20,CA Davis (WI),5,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,WI),CA Davis,1968,1973
21,VG Kambli (IND),2,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,IND),VG Kambli,1993,1995
22,GS Chappell (AUS),14,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,AUS),GS Chappell,1970,1984
23,AD Nourse (SA),16,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,SA),AD Nourse,1935,1951
24,SR Tendulkar (IND),24,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,IND),SR Tendulkar,1989,2013
25,BC Lara (ICC/WI),16,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,ICC/WI),BC Lara,1990,2006
26,YBK Jaiswal (IND),2,19,36,2,1798,214,52.88,2738,65.66,4,10,3,207,39,IND),YBK Jaiswal,2023,2025
27,Javed Miandad (PAK),17,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,PAK),Javed Miandad,1976,1993
28,R Dravid (ICC/IND),16,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,ICC/IND),R Dravid,1996,2012
29,Mohammad Yousuf (PAK),12,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,PAK),Mohammad Yousuf,1998,2010
30,Younis Khan (PAK),17,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,PAK),Younis Khan,2000,2017
31,RT Ponting (AUS),17,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,AUS),RT Ponting,1995,2012
32,J Ryder (AUS),9,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,AUS),J Ryder,1920,1929
33,A Flower (ZIM),10,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,ZIM),A Flower,1992,2002
34,MEK Hussey (AUS),8,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,AUS),MEK Hussey,2005,2013
35,S Chanderpaul (WI),21,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,WI),S Chanderpaul,1994,2015
36,SM Gavaskar (IND),16,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,IND),SM Gavaskar,1971,1987
37,SR Waugh (AUS),19,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,AUS),SR Waugh,1985,2004
38,JE Root (ENG),12,152,278,23,12972,262,50.87,22568,57.47,36,65,13,1394,45,ENG),JE Root,2012,2024
39,ML Hayden (AUS),15,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,AUS),ML Hayden,1994,2009
40,AB de Villiers (SA),14,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,SA),AB de Villiers,2004,2018
41,AR Border (AUS),16,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,AUS),AR Border,1978,1994
42,Saud Shakeel (PAK),3,19,36,3,1658,208,50.24,3345,49.56,4,9,2,165,2,PAK),Saud Shakeel,2022,2025
43,IVA Richards (WI),17,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,WI),IVA Richards,1974,1991
44,DCS Compton (ENG),20,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,ENG),DCS Compton,1937,1957
45,DPMD Jayawardene (SL),17,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,SL),DPMD Jayawardene,1997,2014
46,Inzamam-ul-Haq (ICC/PAK),15,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,ICC/PAK),Inzamam-ul-Haq,1992,2007
47,FMM Worrell (WI),15,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,WI),FMM Worrell,1948,1963
48,CP Mead (ENG),17,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,ENG),CP Mead,1911,1928
49,V Sehwag (ICC/IND),12,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,ICC/IND),V Sehwag,2001,2013
50,Abid Ali (PAK),2,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,PAK),Abid Ali,2019,2021
51,MJ Clarke (AUS),11,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,AUS),MJ Clarke,2004,2015
52,KC Bland (SA),5,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,SA),KC Bland,1961,1966
53,B Mitchell (SA),20,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,SA),B Mitchell,1929,1949
54,Hon.FS Jackson (ENG),12,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,ENG),Hon.FS Jackson,1893,1905
55,TT Samaraweera (SL),12,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,SL),TT Samaraweera,2001,2013
56,RN Harvey (AUS),15,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,AUS),RN Harvey,1948,1963
57,KD Walters (AUS),16,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS),KD Walters,1965,1981
58,GC Smith (ICC/SA),12,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith,2002,2014
59,WH Ponsford (AUS),10,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS),WH Ponsford,1924,1934
60,SJ McCabe (AUS),8,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS),SJ McCabe,1930,1938
61,DR Jardine (ENG),6,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG),DR Jardine,1928,1934

In [32]:
df

,Player,Duration,Matches,Inns,NO,Runs,High_score,Ave,Balls_faced,Strike_rate,100,50,0,4s,6s,country,start_year,end_year
0,DG Bradman,20,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS),1928,1948
1,PHKD Mendis,3,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL),2022,2025
2,AC Voges,1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),2015,2016
3,RG Pollock,7,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA),1963,1970
4,GA Headley,24,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI),1930,1954
5,H Sutcliffe,11,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG),1924,1935
6,E Paynter,8,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG),1931,1939
7,KF Barrington,13,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG),1955,1968
8,ED Weekes,10,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,WI),1948,1958
9,HC Brook,2,24,40,1,2281,317,58.48,2581,88.37,8,10,2,246,37,ENG),2022,2024
10,WR Hammond,20,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG),1927,1947
11,GS Sobers,20,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,WI),1954,1974
12,KC Sangakkara,15,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,SL),2000,2015
13,JB Hobbs,22,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,ENG),1908,1930
14,SPD Smith,15,116,206,25,10271,239,56.74,19176,53.56,36,41,11,1116,61,AUS),2010,2025
15,CL Walcott,12,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,WI),1948,1960
16,L Hutton,18,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,ENG),1937,1955
17,JH Kallis,18,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,ICC/SA),1995,2013
18,GE Tyldesley,8,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,ENG),1921,1929
19,KS Williamson,14,105,186,17,9276,251,54.88,17913,51.78,33,37,11,1031,27,NZ),2010,2024
20,CA Davis,5,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,WI),1968,1973
21,VG Kambli,2,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,IND),1993,1995
22,GS Chappell,14,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,AUS),1970,1984
23,AD Nourse,16,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,SA),1935,1951
24,SR Tendulkar,24,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,IND),1989,2013
25,BC Lara,16,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,ICC/WI),1990,2006
26,YBK Jaiswal,2,19,36,2,1798,214,52.88,2738,65.66,4,10,3,207,39,IND),2023,2025
27,Javed Miandad,17,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,PAK),1976,1993
28,R Dravid,16,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,ICC/IND),1996,2012
29,Mohammad Yousuf,12,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,PAK),1998,2010
30,Younis Khan,17,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,PAK),2000,2017
31,RT Ponting,17,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,AUS),1995,2012
32,J Ryder,9,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,AUS),1920,1929
33,A Flower,10,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,ZIM),1992,2002
34,MEK Hussey,8,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,AUS),2005,2013
35,S Chanderpaul,21,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,WI),1994,2015
36,SM Gavaskar,16,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,IND),1971,1987
37,SR Waugh,19,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,AUS),1985,2004
38,JE Root,12,152,278,23,12972,262,50.87,22568,57.47,36,65,13,1394,45,ENG),2012,2024
39,ML Hayden,15,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,AUS),1994,2009
40,AB de Villiers,14,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,SA),2004,2018
41,AR Border,16,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,AUS),1978,1994
42,Saud Shakeel,3,19,36,3,1658,208,50.24,3345,49.56,4,9,2,165,2,PAK),2022,2025
43,IVA Richards,17,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,WI),1974,1991
44,DCS Compton,20,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,ENG),1937,1957
45,DPMD Jayawardene,17,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,SL),1997,2014
46,Inzamam-ul-Haq,15,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,ICC/PAK),1992,2007
47,FMM Worrell,15,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,WI),1948,1963
48,CP Mead,17,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,ENG),1911,1928
49,V Sehwag,12,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,ICC/IND),2001,2013
50,Abid Ali,2,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,PAK),2019,2021
51,MJ Clarke,11,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,AUS),2004,2015
52,KC Bland,5,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,SA),1961,1966
53,B Mitchell,20,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,SA),1929,1949
54,Hon.FS Jackson,12,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,ENG),1893,1905
55,TT Samaraweera,12,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,SL),2001,2013
56,RN Harvey,15,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,AUS),1948,1963
57,KD Walters,16,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS),1965,1981
58,GC Smith,12,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),2002,2014
59,WH Ponsford,10,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS),1924,1934
60,SJ McCabe,8,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS),1930,1938
61,DR Jardine,6,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG),1928,1934

In [3]:
df.rename(columns={"Ave":"Average"},inplace=True)

NameError: name 'df' is not defined

In [2]:
df.to_csv("newcricinfo.csv", index=False)

NameError: name 'df' is not defined

In [4]:
df

NameError: name 'df' is not defined

In [9]:
df

,Player,Duration,Matches,Inns,NO,Runs,High_score,Ave,Balls_faced,Strike_rate,100,50,0,4s,6s,country,start_year,end_year
0,DG Bradman,20,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS),1928,1948
1,PHKD Mendis,3,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL),2022,2025
2,AC Voges,1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),2015,2016
3,RG Pollock,7,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA),1963,1970
4,GA Headley,24,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI),1930,1954
5,H Sutcliffe,11,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG),1924,1935
6,E Paynter,8,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG),1931,1939
7,KF Barrington,13,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG),1955,1968
8,ED Weekes,10,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,WI),1948,1958
9,HC Brook,2,24,40,1,2281,317,58.48,2581,88.37,8,10,2,246,37,ENG),2022,2024
10,WR Hammond,20,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG),1927,1947
11,GS Sobers,20,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,WI),1954,1974
12,KC Sangakkara,15,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,SL),2000,2015
13,JB Hobbs,22,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,ENG),1908,1930
14,SPD Smith,15,116,206,25,10271,239,56.74,19176,53.56,36,41,11,1116,61,AUS),2010,2025
15,CL Walcott,12,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,WI),1948,1960
16,L Hutton,18,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,ENG),1937,1955
17,JH Kallis,18,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,ICC/SA),1995,2013
18,GE Tyldesley,8,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,ENG),1921,1929
19,KS Williamson,14,105,186,17,9276,251,54.88,17913,51.78,33,37,11,1031,27,NZ),2010,2024
20,CA Davis,5,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,WI),1968,1973
21,VG Kambli,2,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,IND),1993,1995
22,GS Chappell,14,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,AUS),1970,1984
23,AD Nourse,16,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,SA),1935,1951
24,SR Tendulkar,24,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,IND),1989,2013
25,BC Lara,16,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,ICC/WI),1990,2006
26,YBK Jaiswal,2,19,36,2,1798,214,52.88,2738,65.66,4,10,3,207,39,IND),2023,2025
27,Javed Miandad,17,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,PAK),1976,1993
28,R Dravid,16,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,ICC/IND),1996,2012
29,Mohammad Yousuf,12,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,PAK),1998,2010
30,Younis Khan,17,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,PAK),2000,2017
31,RT Ponting,17,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,AUS),1995,2012
32,J Ryder,9,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,AUS),1920,1929
33,A Flower,10,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,ZIM),1992,2002
34,MEK Hussey,8,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,AUS),2005,2013
35,S Chanderpaul,21,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,WI),1994,2015
36,SM Gavaskar,16,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,IND),1971,1987
37,SR Waugh,19,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,AUS),1985,2004
38,JE Root,12,152,278,23,12972,262,50.87,22568,57.47,36,65,13,1394,45,ENG),2012,2024
39,ML Hayden,15,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,AUS),1994,2009
40,AB de Villiers,14,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,SA),2004,2018
41,AR Border,16,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,AUS),1978,1994
42,Saud Shakeel,3,19,36,3,1658,208,50.24,3345,49.56,4,9,2,165,2,PAK),2022,2025
43,IVA Richards,17,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,WI),1974,1991
44,DCS Compton,20,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,ENG),1937,1957
45,DPMD Jayawardene,17,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,SL),1997,2014
46,Inzamam-ul-Haq,15,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,ICC/PAK),1992,2007
47,FMM Worrell,15,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,WI),1948,1963
48,CP Mead,17,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,ENG),1911,1928
49,V Sehwag,12,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,ICC/IND),2001,2013
50,Abid Ali,2,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,PAK),2019,2021
51,MJ Clarke,11,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,AUS),2004,2015
52,KC Bland,5,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,SA),1961,1966
53,B Mitchell,20,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,SA),1929,1949
54,Hon.FS Jackson,12,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,ENG),1893,1905
55,TT Samaraweera,12,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,SL),2001,2013
56,RN Harvey,15,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,AUS),1948,1963
57,KD Walters,16,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS),1965,1981
58,GC Smith,12,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),2002,2014
59,WH Ponsford,10,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS),1924,1934
60,SJ McCabe,8,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS),1930,1938
61,DR Jardine,6,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG),1928,1934

In [12]:
df.rename(columns={"Ave":"Average"},inplace=True)

In [13]:
df

,Player,Duration,Matches,Inns,NO,Runs,High_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country,start_year,end_year
0,DG Bradman,20,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS),1928,1948
1,PHKD Mendis,3,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL),2022,2025
2,AC Voges,1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),2015,2016
3,RG Pollock,7,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA),1963,1970
4,GA Headley,24,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI),1930,1954
5,H Sutcliffe,11,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG),1924,1935
6,E Paynter,8,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG),1931,1939
7,KF Barrington,13,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG),1955,1968
8,ED Weekes,10,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,WI),1948,1958
9,HC Brook,2,24,40,1,2281,317,58.48,2581,88.37,8,10,2,246,37,ENG),2022,2024
10,WR Hammond,20,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG),1927,1947
11,GS Sobers,20,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,WI),1954,1974
12,KC Sangakkara,15,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,SL),2000,2015
13,JB Hobbs,22,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,ENG),1908,1930
14,SPD Smith,15,116,206,25,10271,239,56.74,19176,53.56,36,41,11,1116,61,AUS),2010,2025
15,CL Walcott,12,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,WI),1948,1960
16,L Hutton,18,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,ENG),1937,1955
17,JH Kallis,18,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,ICC/SA),1995,2013
18,GE Tyldesley,8,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,ENG),1921,1929
19,KS Williamson,14,105,186,17,9276,251,54.88,17913,51.78,33,37,11,1031,27,NZ),2010,2024
20,CA Davis,5,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,WI),1968,1973
21,VG Kambli,2,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,IND),1993,1995
22,GS Chappell,14,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,AUS),1970,1984
23,AD Nourse,16,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,SA),1935,1951
24,SR Tendulkar,24,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,IND),1989,2013
25,BC Lara,16,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,ICC/WI),1990,2006
26,YBK Jaiswal,2,19,36,2,1798,214,52.88,2738,65.66,4,10,3,207,39,IND),2023,2025
27,Javed Miandad,17,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,PAK),1976,1993
28,R Dravid,16,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,ICC/IND),1996,2012
29,Mohammad Yousuf,12,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,PAK),1998,2010
30,Younis Khan,17,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,PAK),2000,2017
31,RT Ponting,17,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,AUS),1995,2012
32,J Ryder,9,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,AUS),1920,1929
33,A Flower,10,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,ZIM),1992,2002
34,MEK Hussey,8,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,AUS),2005,2013
35,S Chanderpaul,21,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,WI),1994,2015
36,SM Gavaskar,16,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,IND),1971,1987
37,SR Waugh,19,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,AUS),1985,2004
38,JE Root,12,152,278,23,12972,262,50.87,22568,57.47,36,65,13,1394,45,ENG),2012,2024
39,ML Hayden,15,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,AUS),1994,2009
40,AB de Villiers,14,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,SA),2004,2018
41,AR Border,16,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,AUS),1978,1994
42,Saud Shakeel,3,19,36,3,1658,208,50.24,3345,49.56,4,9,2,165,2,PAK),2022,2025
43,IVA Richards,17,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,WI),1974,1991
44,DCS Compton,20,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,ENG),1937,1957
45,DPMD Jayawardene,17,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,SL),1997,2014
46,Inzamam-ul-Haq,15,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,ICC/PAK),1992,2007
47,FMM Worrell,15,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,WI),1948,1963
48,CP Mead,17,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,ENG),1911,1928
49,V Sehwag,12,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,ICC/IND),2001,2013
50,Abid Ali,2,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,PAK),2019,2021
51,MJ Clarke,11,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,AUS),2004,2015
52,KC Bland,5,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,SA),1961,1966
53,B Mitchell,20,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,SA),1929,1949
54,Hon.FS Jackson,12,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,ENG),1893,1905
55,TT Samaraweera,12,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,SL),2001,2013
56,RN Harvey,15,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,AUS),1948,1963
57,KD Walters,16,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS),1965,1981
58,GC Smith,12,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),2002,2014
59,WH Ponsford,10,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS),1924,1934
60,SJ McCabe,8,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS),1930,1938
61,DR Jardine,6,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG),1928,1934

In [14]:
df.to_csv("newcricinfo.csv", index=False)